import "./globals.css";

export const metadata = {
  title: "Blueprint Realities",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
